version: '3.8'

services:
  backend:
    image: prabhav018/cleanindia-backend:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/cleanindia # Use the mongo service name
      # Add other necessary environment variables here, e.g., JWT_SECRET, CLOUDINARY details
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    image: prabhav018/cleanindia-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:6.0 # You can adjust the version based on your needs
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
